version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: spencer-framework_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Lint"
          command: yarn lint:ci

      - run:
          name: "Test"
          command: yarn test:ci

      - store_artifacts:
          path: coverage
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - codecov/upload:
          file: coverage/lcov.info